language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_install:
  - cp tests/phpunit.travis.xml tests/phpunit.xml
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: ./tests/runtests.sh

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt

